### ISSUE TITLE
Mind deleting this repo?

### ISSUE THREAD

**Issue by sleeyax** [Ivshti/stremio-addon#1]
I'm embarrassed to ask, but do you mind deleting this repo so my fork (the rust addon sdk) becomes the parent repository? (see: [deleting-a-public-repository](https://help.github.com/en/github/collaborating-with-issues-and-pull-requests/what-happens-to-forks-when-a-repository-is-deleted-or-changes-visibility#deleting-a-public-repository))

My fork has become something of its own and has diverged a lot from this repo. I could create a copy but then I'll loose all issues, so this way would be less of a hassle for me.

**Comment by Ivshti** [comment]
It's not a problem for me to delete it and then repush it under a different name
